FROM alpine:3.19

RUN apk add --no-cache ca-certificates

COPY alchemist /usr/local/bin/alchemist

RUN ln -s /usr/local/bin/alchemist /usr/bin/alchemist
RUN ln -s /usr/local/bin/alchemist /alchemist

ENTRYPOINT ["alchemist"]
CMD ["--help"]